# Generated by Django 3.1.1 on 2021-01-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvCourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ratings',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***')]),
        ),
    ]
